/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.google.firebase;

import java.io.FilterInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.File;
import java.util.Scanner;
import java.util.concurrent.ExecutionException;

import com.google.api.core.ApiFuture;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.WriteResult;

import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.cloud.FirestoreClient;
import com.google.firebase.IncomingHttpResponse;
import com.google.firebase.OutgoingHttpRequest;
import com.google.firebase.ThreadManager;
import com.google.firebase.ErrorCode;
import com.google.firebase.FirebaseException;


public class firebase {
    public static void main(String[] args) throws IOException, InterruptedException, ExecutionException {
    	FileInputStream serviceAccount = new FileInputStream("C:/Users/semihbu/eclipse-workspace2/vestel-ajak-sdk-firebase-adminsdk.json");
    	
    	FirebaseOptions options = new FirebaseOptions.Builder()
    			.setCredentials(GoogleCredentials.fromStream(serviceAccount))
    			.setDatabaseUrl("https://vestel-ajak-sdk.firebaseio.com")
    			.build();

    			FirebaseApp.initializeApp(options);
    			Firestore db = FirestoreClient.getFirestore();
    			
    			String collectionPath;
				DocumentReference docRef = db.collection(collectionPath:"pairedDevice").document("pairedDevicedata");
    			//asynchronously retrieve the document
    			ApiFuture<DocumentSnapshot> future = docRef.get();
    			//...
    			//future.get() blocks on response
    			DocumentSnapshot document = future.get();
    			if (document.exists()) {
    			System.out.println("Document data: " + document.getData());
    			} else {
    			System.out.println("No such document!");
    			
    } 

	
		
	}
}


